### ISSUE TITLE
Error Message for no providers available needs to be updated.

### ISSUE THREAD

**Issue by KKAY99** [hungernotimpossible/hni#108] opened 2016-12-01 01:36 UTC
![screenshot_20161130-185348](https://cloud.githubusercontent.com/assets/10553982/20778548/fc32f9e0-b733-11e6-8130-d3839f66b6ba.png)

**Comment by darargon** [comment] 2016-12-01 14:43
That's actually the message you get if it found locations, but none of them had a menu that registered as current. If you're phone is in eastern time, then it would be 11:53 UTC, which would mean this is caused by issue #97 .

**Comment by KKAY99** [comment] 2016-12-01 14:59
The concern was more on the text of the message - "All providers there are
not currently available".  Not the clearest message.  Perhaps something
like "There are no nearby providers currently available to order from."

**Comment by darargon** [comment] 2016-12-01 15:09
That's fair, I was looking at the code and it seems someone already changed it. It now reads "Providers currently unavailable. Reply with new address or try again later. Reply ENDMEAL to quit."

**Comment by john3parker** [comment] 2016-12-02 01:27
I updated the text messages. Closing this ticket.

**Closed by john3parker** 2016-12-02 01:27 UTC
